export enum CommandIds {
  ChangeWorkspace = 'changeWorkspace',
  GenerateClass = 'generateClass',
  GenerateInterface = 'generateInterface',
  GenerateEnum = 'generateEnum',
  GenerateType = 'generateType',
  GenerateFunction = 'generateFunction',
  GenerateVariable = 'generateVariable',
  GenerateCustomComponent = 'generateCustomComponent',
  GenerateNodeModule = 'generateNodeModule',
  GenerateNodeServer = 'generateNodeServer',
  GenerateExpressController = 'generateExpressController',
  GenerateExpressMiddleware = 'generateExpressMiddleware',
  GenerateExpressRoute = 'generateExpressRoute',
  GenerateExpressServer = 'generateExpressServer',
  GenerateFastifyController = 'generateFastifyController',
  GenerateFastifyMiddleware = 'generateFastifyMiddleware',
  GenerateFastifyRoute = 'generateFastifyRoute',
  GenerateFastifyServer = 'generateFastifyServer',
  GenerateReactComponent = 'generateReactComponent',
}
